apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USER_SERVICE_URL: "http://user-service:8001"
  FILE_SERVICE_URL: "http://file-service:8002"
  QUESTION_SERVICE_URL: "http://question-service:8003"
  NEXT_PUBLIC_API_URL: "http://api.example.com/api"
